### ISSUE TITLE
Question with SaveChangesAsync in AppDbContext 

### ISSUE THREAD

**Issue by mmasdivins** [ardalis/CleanArchitecture#140]
If the domain events are events that can modify something of the aggregate model the `int result = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);` should be called at the end of the function to ensure the changes are contained in a single transaction.

Maybe the domain events should be changed to identify if it needs to be integrated in the same transaction or after(?).

**Comment by DaveShopCtrl** [comment]
Most database frameworks support the System.Transaction namespace. Just create an explicit primary transaction in your (entry) call to your domain service method. Each domain service is responsible for its own transaction. Because your already create a transaction, your domain service transactions are basically turned into sub-transactions.

Your primary transaction Complete() call will commit the primary transaction and it's sub transactions. If any of the indirect domain services throws an exception, your just don't call the Complete method and all sub transactions are rolled back automatically.

Providing a flag that the domain event should be part of a transaction is not enough. You than actually need to pass along a transaction and that makes it harder to later move to MongoDB.

Each domain should be isolated and not even be loosely couples to other domains. The System.Transaction namespace provide you a common transaction framework where each domain just perform it's own logic. Domain event handlers can call other domains and those transaction are enlisted into the primary transaction. This allows you to even mix relational- and document database transactions (provided that all drivers support System.Transaction)..

**Comment by mmasdivins** [comment]
I don't really get how the System.Transaction works with multiple domain services. I have for example this two domain services:
`
public class OrderService : IOrderService
{

    private readonly IAsyncRepository _orderRepository;

    public OrderService(IAsyncRepository orderRepository)
    {
        _orderRepository = orderRepository;
    }

    public async Task CreateOrder(int clientId, int productId, int qty)
    {
        using (TransactionScope scope = new TransactionScope())
        {
            await _orderRepository.AddAsync(clientId, productId, qty);
            scope.Complete();
        }
    }
}


public class StockService : IStockService
{

    private readonly IAsyncRepository _stockRepository;

    public StockService(IAsyncRepository stockRepository)
    {
        _stockRepository = stockRepository;
    }

    public async Task UpdateStock(int productId, int qty)
    {
        using (TransactionScope scope = new TransactionScope())
        {
            var stock = await _orderRepository.GetByIdAsync(productId);
            if (stock.Quantity > qty)
            {
                stock.Quantity -= qty;
                await _orderRepository.UpdateAsync(stock);

                // Only if we can update
                scope.Complete();
            }
        }

    }
}`

The order service creates an order and the stock service updates the stock of an specific product. 

Now if we create and order from the OrderService the Order entity creates an event to update the stock:
`public class Order : BaseEntity
{
    // Fields
    public int ProductId { get; private set; }
    public int Quantity { get; private set; }

    public Order(int productId, int qty)
    {
        ProductId = productId;
        Quantity = qty;
    }

    // Methods
    public void CreateOrder()
    {
        Events.Add(new OrderCreatedEvent(this, ProductId, Quantity));
    }
}`

And the handler of this event calls the StockService function to update the stock:
`public class OrderCreatedEventHandler : INotificationHandler<OrderCreatedEvent>
{
    private readonly IStockService _stockService;
    private readonly IRepository _repository;


    public OrderCreatedEventHandler(IRepository repository, IStockService stockService)
    {
        _repository = repository;
        _stockService = stockService;
    }

    public async Task Handle(OrderCreatedEvent domainEvent, CancellationToken cancellationToken)
    {
        Guard.Against.Null(domainEvent, nameof(domainEvent));
        await _stockService.UpdateStock(domainEvent.ProductId, domainEvent.Quantity);
    }
}`

Will the call to the CreateOrder of the OrderService be in the same transaction scope as the UpdateStock of the StockService.

This is not the best example and I just put the minimum to show my questions.
Thanks for your reply!

**Comment by DaveShopCtrl** [comment]
You also have to create a primary transaction that lives outside the services. 'Somewhere' you have created an instance of Order. Without knowing the rest of your code, this would be the most logical place to create that primary transaction. Inside that transaction you kickoff the event change (i.e. order.CreateOrder()).

Because EF has support for System.Transaction, both IAsyncRepository instances used in OrderService and StockService would be enlisted in the transaction. DbContext does this enlisting automatically..

Normally you only have a transaction per aggregate root. Using TransactionScope (UnitOfWork pattern) is technically a workaround (and violation of DDD-principles as you need to introduce 'database' logic into your application and that is what we normally try to avoid hence the database repository. It should hide HOW and WHERE data is stored..

Personally I like to use workflows (workflow-core) to orchestrate cross boundary concerns or use a saga manager like MassTransit. That way your domain events truly act like a notification service. The great thing about workflows is that after your order is saved, the stock is changed, if this task fails, you can employ various techniques to restore to a previous or different state. Transactions are more like an all or nothing approach..

Let me pose a different question. Do you want to rollback the save action of the Order entity (i.e. delete the order) when you're out of stock? In most cases you want to keep the order and in the case that stock cannot be allocated, you can send an email to the customer that the product is out of stock and you try to fulfill the order as soon as possible or you can refund the customer..

I try to view services like independent micro services that are running somewhere and cannot communicate with each other. About 9 months ago I stumbled upon the eShopOnContainers sample website: https://github.com/dotnet-architecture/eShopOnContainers. 

This is the same shop as Ardalis created using his clean architecture 'framework' (https://github.com/dotnet-architecture/eShopOnWeb), but now divided my more visible boundaries.. 

I think that the Microsoft commissioned eShop implementations are a great introduction of various techniques how to create modern websites..

**Comment by mmasdivins** [comment]
Thanks for your response! 
I understand better how it works, I suppose the decision to use a primary transaction or a workflow or saga manager depends if you want to commit all if success or rollback all if fail. If you don't have intermeditate states maybe using a saga or a worflow will be overkill.

**Comment by ardalis** [comment]
Thanks for the great answers, @DaveShopCtrl ! Closing this now but feel free to follow up if you have more questions, @mmasdivins .
