### ISSUE TITLE
Question about CleanArchitecture.UnitTests

### ISSUE THREAD

**Issue by marcelremmers** [ardalis/CleanArchitecture#141]
Hey,
why do you use a mock for the IRepository?
Can't we just reimplement the IRepository that returns test data?

Best regards

**Comment by DaveShopCtrl** [comment]
Hi Marcel,

IRepository itself is not generic, but it members are. This makes it harder to write fakes.
But there is nothing stopping you from using fakes instead of mocked objects.

Personally I'm more fond of mocking because the mock framework I use (Moq) has a strict option. Meaning that any call to the object that is not explicitly setup, will make sure the test fails. This kind of behavior is very hard to write using fakes. This is only possible if you write specific fakes/stubs for each test..

Maybe you are a bit confused because the standard template only has one entity type (ToDoItem). The idea is that every service in the same context (let's say http request) get the same instance of IRepository and it can be used for all database operation regardless of the entity: 

```
var repository = container.Get<IRepository>(); //This is considered an anti-pattern (service locator), but keeps code concise..
var incompleteItems = await repository.ListAsync(new IncompleteItemsSpecificatio()); //query ToDoItems table
var usersWithoutItems = await repository.ListAsync(new UsersWithoutToDoItems()); //query Users table
```

You might want to analyze to EShopOnWeb code https://github.com/dotnet-architecture/eShopOnWeb. That is a e-commerce website build on the clean architecture 'framework'. The UnitTests of this project are just added so that you have a head start..

Hope this helps

**Comment by ardalis** [comment]
Good point about the template having only one entity type. Maybe I should add a parent type or something to add complexity. The challenge is that this is meant to be a solution template, not a sample project, and everything I add to it for educational purposes just adds to the number of things that need to be removed to use it for your real project. Checking out eShopOnWeb is good advice.

There's not really much practical difference between writing your own implementation that returns fake data (a Fake) and using a dynamically generated type to do the same thing (a Mock). Use whichever you're more comfortable with.
