### ISSUE TITLE
How many Project should Application Layer have? 

### ISSUE THREAD

**Issue by lehoangphan** [ardalis/CleanArchitecture#145]
If our enterprise has 5 applications (example: clientWeb, clientMobile, OperatorWeb, logisticWeb,ReportMobile), 

how many projects should Application Layer should have? If we use Clean Architecture

more than 5 projects in Application Layer + 5 in Presentation layer

Or 

 1 project in Application Layer + 5 projects in Presentation ? 

Because I just see 1 projects in Application + 2 In Presentation (this template) 

Thanks

**Comment by ardalis** [comment]
Typically I recommend having one Solution per Application that you ship/deploy. And this is a solution template. So if you have 5 applications I would have 5 solutions each with Core/Infrastructure/Web. If you find having a distinct application layer valuable, then add that as well - total of 4 (non-test) projects per solution.

But what about shared code!

That's what a SharedKernel project is for, which should be in a separate solution and should publish a NuGet package that the other solutions consume. If it's early days and you're just getting started, a high-churn NuGet package is going to slow you down, so in early rampup of the project it's fine to just add it as a class library to your first solution or two. But once things get a bit more stable, you'll want it to be just a NuGet reference rather than a class library.

**Comment by lehoangphan** [comment]
Thanks for your recommend!
