### ISSUE TITLE
db request

### ISSUE THREAD

**Issue by yoni536** [ardalis/CleanArchitecture#150]
how can I update the db to use DynamoDB (aws)
dynamodb info:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CRUDHighLevelExample1.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NET.html
https://www.youtube.com/watch?v=B190tcu1ERk
http://cdn.cdata.com/help/DDE/ado/pg_usingEFCoreIntro.htm

**Comment by lehoangphan** [comment]
I stuck this problem before, because in this template the Specification Pattern just working with Base-lambda ORM (ISPecification<T>)

but DynamoDb SDK is non-linq library, it has no Where overload, Select .. etc 

So If use this template, work with dynamo db, you just juse traditional Repository pattern, can not use Specification Pattern 

And you can not Abstraction for all Repository if you work with DynamoDb, every UpdateAsync() in your Repository, you must override

**Comment by ardalis** [comment]
Every database option has tradeoffs.

**Comment by ardalis** [comment]
Anyway, the only thing you would change is how you get data. Just replace the IRepository usage with your own version and implementation. Even if it means you need a separate implementation of each CRUD operation per entity type you have. The architecture and layout and separate of concerns all still works. You just don't have a handy ORM to use to reduce how much code you need to write yourself.
