### ISSUE TITLE
Repository in Asp Core Clean Architecture

### ISSUE THREAD

**Issue by asgharb** [ardalis/CleanArchitecture#163]
hi.
I was a bit confused.
I read somewhere that the Repository template has been implemented inside Ef Core and we no longer need to use Repository in asp core and only use services in the Application layer.
For example, a folder should be created for the user and all tasks and services related to the user, such as registration, deletion, etc., should be implemented by these services, which themselves work directly with DbContext.

Is the use of Repository obsolete in clean architecture and Ef Core?

**Comment by ardalis** [comment]
> Is the use of Repository obsolete in clean architecture and Ef Core?

No, there is just bad information available on the internet. Some developers have noted that, because you can perform data access operations using a dbContext, and because Repository is a data access pattern, that the two are one and the same. They misunderstand the pattern.

The Repository pattern's usefulness arises from the fact that it allows your code to depend on an abstraction that you control. The abstraction, not the implementation, is the point of the pattern and where it gets its value, because it provides a *seam* you can use for testing and interception (via decorators, etc.).

I talk about this in these podcast episodes (they're short - on YouTube):

- [Do you need a Repository](https://www.youtube.com/watch?v=FbYYz5i_B_Y)
- [What Good is a Repository?](https://www.youtube.com/watch?v=-O_WVzkLtAA)
- [Layering Patterns on Repositories](https://www.youtube.com/watch?v=_eICIBt5rkw)

**Comment by jbogard** [comment]
In PoEAA terms:

DbSet = [Repository](https://martinfowler.com/eaaCatalog/repository.html)
DbContext = [Unit of Work](https://martinfowler.com/eaaCatalog/unitOfWork.html)
Change Tracker = [Identity Map](https://martinfowler.com/eaaCatalog/identityMap.html)

In NHibernate, the `ISession` interface does the first two, and an internal object does the last, but is scoped to an `ISession`.

Repository is a bit of an overloaded term these days, so you have to specify the context. I use the PoEAA definitions since that was what I originally learned and, and it's the same thing the original DDD book refers to. So I'll say "Fowler repository" if there's ambiguity.

If we're talking about the Clean/Onion/Hexagonal architecture repository pattern, I tend to use the term "Abstract Repository" because it has additional goals over the original repository pattern as noted above.

**Comment by ardalis** [comment]
From your link (Fowler - Repository), consider this image:

![image](https://user-images.githubusercontent.com/782127/110959250-7f6ae680-831b-11eb-9f57-41ee67d39e90.png)

It includes a "Repository" which is abstract in terms of implementation details, and a specific _strategy_ (in this case an in memory strategy). The text also specifies:

> A Repository mediates between the domain and data mapping layers, acting like an in-memory domain object collection. Client objects construct query _specifications_ declaratively and submit them to Repository for satisfaction.

**The Repository is separate from and wraps the concrete strategy or implementation details of how the data is stored and retrieved.**

From Evans' DDD:

> For each type of object that needs global access, create an object that can provide the illusion of an in-memory collection of all objects of that type. Set up access through a well-known global interface.

Now, you could argue that each DbSet is the object (that provides the illusion...) and perhaps then argue that the "well-known global interface" is the DbContext, but **I think that's a stretch**. Especially when Evans goes on to list advantages of repositories:

> They decouple application and domain design from persistence technology, multiple database strategies, or even multiple data sources.

What is EF, or NHibernate, or Dapper if not a "persistence technology"? 
How can one claim to be decoupled from these if one takes a direct dependency on one of them?

**Since code that directly depends on these persistence technologies is not decoupled from them, and since that decoupling is cited as an advantage of using Repositories, it's clear that doing so is not following the Repository Pattern.**

There is no separate "abstract repository" pattern. There are repository interfaces (or abstractions), their implementations, and data access technologies. Unfortunately Fowler's diagram shows only a sequence diagram, not a class relationship diagram, or it would be (even more) apparent that this is the case. Since it only shows concrete types, not the abstractions or interfaces used to stitch them together at compile time, we must reach this conclusion through other means.

Maybe he can weigh in here - @martinfowler ? ericevans0 ?

**Comment by jbogard** [comment]
The implementation details in .NET/.NET Core-land is ADO junk. DbSet checks all those boxes. LINQ is the query specification. DbSet mediates between domain layer and data mapping layers (that's internal to the ORM). Using a DbSet means my application is abstracted from the implementation (ADO and SQL).

Or (N)Hibernate, there's several different ways to specify the query in domain terms, and have it translated to provider-specific terms.

Remember, the PoEAA names predate any Hexagonal/Onion/Clean terms/patterns. And those names were describing software libraries and patterns that already existed.

The point of the repository pattern, originally, was to encapsulate *SQL* not *ORMs*.

**Comment by jbogard** [comment]
BTW it might not be clear in the abridged version in the link, but it's very clear from the book. However what is not as obvious is that swapping implementations might not be as possible as described in the book. One can't simply (dot gif meme) swap a relational database for a web service for a document database for in memory collections etc etc

**Comment by ardalis** [comment]
Right, the inability to swap out implementations should be a pretty big clue that it's not following the pattern.

It's also worth noting that Evans shows Repository as being a part of the domain model:
![image](https://user-images.githubusercontent.com/782127/110975551-e396a600-832d-11eb-8c44-ad9bca444929.png)

Now, obviously he's not suggesting that a particular data access library be part of the domain - that would go against the whole idea of having a domain model that is unfettered by infrastructure concerns. So, where in your separate domain model (separate from infrastructure concerns, that is) would you have a *repository* that isn't coupled to (or actually part of) a specific infrastructure library in your "classic repository" pattern you're claiming is separate from an "abstract repository"?

I don't think it's possible. I think the only way you *can* have repositories in your domain model that aren't tied to implementation details, that follow the Dependency Inversion Principle, is for them to be abstract. Hence, the only repository pattern there is or ever was, is the abstract one.
