### ISSUE TITLE
Question: DTOs vs Entities in infrastructure

### ISSUE THREAD

**Issue by SpaceOgre** [ardalis/CleanArchitecture#164]
Hi, 

I have a question about how to go about thinking of entities vs DTOs in the infrastructure layer, mostly repositories at this stage.

Let's say I don't want to load the entire entity for performance reasons, I might have a database view or something else that combines diffrent tables (entities). Is i correct to state that this would be a DTO rather than an entity?

Also what about writes that only handles part of an entity, is it okay to pass an DTO to the Repo for persisting? Or is this breaking some of the principles of clean architecture?

I'm asking because we are in the process of rewriting an old website but the database needs to stay the same for different reasons. I really like the idea of clean architecture but I'm wondering how to go about it, it feels the the lines blur a bit between entities, DTOs

Please let me know if this is an inappropriate question for this repo, I have been looking for a good place to ask and maybe discuss this a bit :)

**Comment by ardalis** [comment]
1. I now have a Stack Overflow tag you can use for questions about this repo: https://stackoverflow.com/questions/tagged/ardalis-cleanarchitecture
2. This is a perfectly fine question to ask here.
3. Repository is a DDD pattern primarily, and I'm using it here in the DDD sense. Which means its abstraction is a part of your domain model and its interface is in terms of that domain model (your entities/aggregates). In DDD, you would never return DTOs, ViewModels, ApiModels, etc. from your repository because those don't belong in your domain model - they are UI or Application concerns. It's not unusual to have a set of ApplicationServices that sits on top of your domain model and is responsible for converting between entities/aggregates and DTOs, if needed. I don't have such a service in this template and in the cases where I use such services I usually just put them in my front end project (Web).
4. If you want to control how much of an entity or aggregate you fetch, use Specification for that. There are examples of this now in the template. This one includes the `Project`'s items for instance: https://github.com/ardalis/CleanArchitecture/blob/main/src/Clean.Architecture.Core/ProjectAggregate/Specifications/ProjectByIdWithItemsSpec.cs

HTH.

**Comment by ardalis** [comment]
PS If you just want to save some ad hoc bit of data without loading its parent aggregate, yes, that breaks DDD rules. That doesn't mean you can't do it, but if I were you I would create a custom interface for that purpose (with a custom implementation) rather than using the Repository abstraction, since the Repository should be working with complete Aggregates by design.

**Comment by SpaceOgre** [comment]
Thank you for taking the time to answer my question and so extensively as well!

Will definitely look into Specifications as it seems really handy :)
