### ISSUE TITLE
IToDoItemSearchService is not used to src code

### ISSUE THREAD

**Issue by MisinformedDNA** [ardalis/CleanArchitecture#166]
Nothing references or uses `IToDoItemSearchService` or its implementation, aside from unit tests. I expected to see it used in `ToDoController`, but it uses `IRepository` instead.

Should `IToDoItemSearchService` be injected into the controller as well, to provide an example of its usage? Wouldn't this be the more common usage anyway?

**Comment by ardalis** [comment]
I should add some way of calling it, yes. It was only added to show how to use specifications, as I recall.

**Comment by benrhere** [comment]
I noticed this as well and was a bit confused. I thought it was an anti-pattern to call from the UI layer (controller) into the repository directly?

Also, could you help me to understand when a service gets implemented in Core, vs in Infrastructure? It looks like in https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures (which references this repo), that services can live in both places according to this diagram: https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/media/image5-7.png

Thanks for any clarification.

**Comment by ardalis** [comment]
I'm doing some heavy refactoring in a current branch that I hope to wrap up on my Twitch stream on Friday afternoon. I'll see if I have time to take care of this then as well.

In terms of referencing the repository abstraction from controllers, that's not an anti-pattern in my opinion. Here's why:

There are a variety of ways to "do work" that involves persistence in a controller action:
1) just talk to the database directly via ADO, Dapper, EF/Core, etc.
2) use a domain abstraction for persistence and work with the domain model types directly
3) go through use cases / application service(s)
M) use MediatR and handlers to do any of the avove
A) do any of the above, but with Ardalis.ApiEndpoints instead of controller actions

I typically start out with 2+A. There's nothing wrong with working with your domain model - that's why you build it. Your repository abstraction, if you have one, is part of that model. Your application layer is not. It's separate. When I need such a thing, I usually put its types in my UI project rather than creating another whole project and layer which most of my operations just pass through. An example of an "as needed" application service can be found here:

https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Services/BasketViewModelService.cs#L28-L38

Why do I put it in the UI layer? Because its methods work with UI layer types like API models and/or ViewModels, which live in the UI project.

Is this the one true correct way? Of course not. But it works well enough in many situations in my experience, and I try to be pragmatic. If there is a problem you're experiencing and introducing a separate use cases or application services layer eliminates that problem without adding more problems that make it not worth the effort, go for it. This template will easily support the addition of one more project and you're quite welcome to fork this repo if you wish.

HTH.

**Comment by benrhere** [comment]
Thanks, that's very helpful. My knowledge about this topic is still not mature so I appreciate the explanation.

> I'm doing some heavy refactoring in a current branch that I hope to wrap up on my Twitch stream on Friday afternoon. 

I've set a reminder to tune in! Looking forward to it.

**Comment by ardalis** [comment]
I haven't gotten to this but I haven't forgotten it either. It's the next thing I intend to do and then I will update the project template.
