### ISSUE TITLE
More info on SharedKernel?

### ISSUE THREAD

**Issue by benrhere** [ardalis/CleanArchitecture#169]
In the readme, you write:

> I recommend creating a separate SharedKernel project and solution if you will require sharing code between multiple projects.

When you mention "multiple projects," are you referring to C# projects (csproj), or something else? Could you give a bit more detail here, such as a scenario where it might make sense to have items in here vs in the core project? I ask because, when I look at the interfaces that are in SharedKernel vs the interfaces that are in Core, I'm not able to surmise a difference between the two. 

Thanks...

**Comment by ardalis** [comment]
That should probably say "solutions" or "software projects" maybe. In DDD lingo this would be "between separate bounded contexts". You might also say "between separate apps" but even that isn't always accurate since many distributed apps are composed of different bounded contexts. So, I guess since it's a DDD term I'll update the README using the DDD terminology. Thanks!

**Comment by ardalis** [comment]
Updated README. Hope that helps.

**Comment by benrhere** [comment]
Thanks for the quick response! That clarification is helpful.

A quick observation: The readme now references "GuGet" which I think may be a typo, and there also remains one mention of the term "project" which you may not have intended.

> It contains types that would likely be shared between multiple projects

Thanks again.

**Comment by ardalis** [comment]
Heh. 2 steps forward, 1 step back.

**Comment by ardalis** [comment]
Fixed.
