### ISSUE TITLE
Where to add ASP.NET Identity

### ISSUE THREAD

**Issue by nyghtrocker** [ardalis/CleanArchitecture#19]
Hi,In which project I will add ASP.NET Identity?. I want to use ASP.NET Identity and wondering where I will add ASP.NET Identity. What you will suggest

**Comment by ardalis** [comment]
It's easiest to add it to the web project. It's not as "pure" that way, since ideally you'd want this non-UI concern to live elsewhere, but it's a lot more work to try and pull it out. You can see an example of having it separate in this sample: https://github.com/dotnet-architecture/eShopOnWeb

In that sample, Identity is kept separate (with its own DbContext) from the rest of the application, too. HTH.
