### ISSUE TITLE
Registering Domain Events

### ISSUE THREAD

**Issue by hugodamiaodias** [ardalis/CleanArchitecture#20]
Hello,
Thank you for this project!
How do you register a listener for domain events in an existing class (as oposed to creating a new class to implement IHandle)?

In a previous example I've seen you do it with the Register method in a Domain Events Class, (e.g.: `DomainEvents.Register<NameOfEventEvent>(Handle);`) , but in this project you seem to have left it out.

How do you achieve it here, and why did you leave it out?
Thank you,
Damião

**Comment by ardalis** [comment]
I prefer to use the convention approach of using handler classes that implement `IHandle<SomeEvent>`. These are wired up automatically, so they don't require an explicit call to `Register`. You can still use that code if the convention doesn't work for some reason (e.g. for an Aggregate event where the aggregate root wants to register for events raised by its children). I didn't include an example of that because this is meant to be a solution template, not a full sample application, and I wanted to minimize how much code folks would need to delete whenever they started a new solution from it. HTH.

**Comment by hugodamiaodias** [comment]
Thank for your pointer. It clarifies the issue. 
The difficulty I'm finding seems to come from the exact exception you referenced.

I have and aggregate root, where I need to listen for the events raised by it's children (in this case to manage the updates), that I have declared as:

`public class ConfApp : BaseEntity, IHandle<ChildUpdatedEvent>`

My hope was to catch the event of the child update on the aggregate root and decide on what happens depending on the condition of the aggregate (with changes to the aggregate being persisted in the same transaction).

When the DomainEventDispatcher.Dispatch tries to dispatch the event I get an exception on `var handlers = _container.GetAllInstances(handlerType);`

Based on the result message (pasted at the end) it would seem that Structure Map tries to reinstanciate the aggregate root, and fails because it would need parameters for that. Starting eith the Id...

If this is the case, would this justify including the `Register` method for the Domain Events, and how could it be updated for this codebase?

Hope this is not too off track... Thanks!

-------
```
Result Message:	
StructureMap.Building.StructureMapBuildException : Error while building type System.Guid.  See the inner exception for details
1.) new Guid(*Default of Byte[]*)
2.) System.Guid
3.) Instance of System.Guid
4.) new ConfApp(*Default of Guid*, *Default of Guid*, *Default of IEnumerable<ChildUpdatedEvent>*)
5.) SIIC.Core.Models.ConfApp.ConfApp
6.) Instance of IHandle<ChildUpdatedEvent> (SIIC.Core.Models.ConfApp.ConfApp)
7.) Container.GetAllInstances(IHandle<ChildUpdatedEvent>)

---- System.ArgumentException : Byte array for GUID must be exactly 16 bytes long.
Parameter name: b
```

**Comment by ardalis** [comment]
I think I see the problem. You're trying to use an aggregate event with a post-persistence domain event pattern (the one I include in this sample by default). I personally distinguish between pre- and post-persistence events, because there are cases in which you want each. Specifically, I classify aggregate events (events raised by children and handled by the root) as pre-persistence since you will likely want to confirm the aggregate is in a valid state prior to persisting it. For the sake of simplicity, I don't include a pre-persistence domain event implementation in this sample. However, you can basically copy Udi's DomainEvents.cs static class from here to get one:
http://udidahan.com/2009/06/14/domain-events-salvation/

Copy that into your SharedKernel and use it from your aggregates. Call DomainEvents.Register in the root app to register for the event and DomainEvents.Raise in the child. Be aware that if you have multiple aggregates in the same thread, by default they will handle one another's events, so you'll want to include some way to detect that an event belongs to your child, not some other aggregate's child.

Hope that helps.

**Comment by hugodamiaodias** [comment]
Pre- and post- persistence events make much more sense. Thank you!
I was convinced that the aproach followed in this project was substituting Udi's DomainEvents.cs static class, but now I understand that they can both be combined.
I was also not aware of the pitfall that multiple aggregates in the same thread can represent and will take that into account. HT!

On question. How do you import the IContainer created of the Startup.cs to Udi's DomainEvents.cs static class?
Because it is a static class it can't be passed as a parameter in the constructor for DI as I would normally do. And the aproach Udi used (below) with the ObjectFactory is incompatible with version 4+ of Structure Map, that is used in this project. Is there a workaround?

```
static DomainEvents()
{
    Container = StructureMap.ObjectFactory.Container;
}
```

**Comment by ardalis** [comment]
Make container a public property and set it in Startup after you configure the container.

**Comment by hugodamiaodias** [comment]
That did it!
Thank you for all the help. This is my first project using DDD, and your material has been most helpful!
In a future iteration of this project, if you find it follows the spirit in which this project was created, you may consider including both types of domain events, as both will likely e needed.
