### ISSUE TITLE
Introduce IApplicationDbContext in the architecture

### ISSUE THREAD

**Issue by HybridSolutions** [ardalis/CleanArchitecture#222]
This is a question / feature request :) 
So if I wanted to have my database context implement an interface and then inject the interface, 

```
public interface IApplicationDbContext
{
    DbSet<Episode> Episodes { get; set; }
    DbSet<ApplicationUser> Users { get; set; }
    int SaveChanges();
    Task<int> SaveChangesAsync(CancellationToken cancellationToken);
}

public class ApplicationDbContext : IdentityDbContext<ApplicationUser>, IApplicationDbContext
{
    public virtual DbSet<Episode> Episodes { get; set; }

    public ApplicationDbContext()
    {
		...
    }
}
```

where would you place this IApplicationDbContext file? It would be interesting to have this in the project since is very common situation.

Thanks

**Comment by ardalis** [comment]
I wouldn't recommend using this approach, personally. If you find it works well for you, by all means, implement it in your own projects. But here are the reasons I would be cautious (most of which relate to [SOLID principles](https://deviq.com/principles/solid)):

- This interface will likely grow every time you add another DbSet/entity. Thus it will violate the Open/Closed Principle (since you need to modify it frequently) and will soon violate the Interface Segregation Principle (since it will become a fat interface and most of its clients won't use all of its methods/properties)
- This interface depends on DbSet, which is an implementation detail. That means the domain model should not depend on this interface (because it would force it to depend on details). This is covered by the Dependency Inversion Principle
- Clean Architecture requires that Core not depend on implementation details (like EF). Thus this interface could not live in Core, but would instead need to live in the Infrastructure project. But that means it could only be used by classes in the Infrastructure project, which probably limits its usefulness (Web/UI should not directly depend on Infrastructure, but on the domain model / Core)

My preference to accomplish the tasks you're describing here is to use [Specification and Repositories](https://github.com/ardalis/Specification). If you need to add UnitOfWork, it's a simple matter to expose a SaveChanges method on your Repository abstraction (without exposing any details about the underlying implementation).

Hope that helps and good luck!

**Comment by HybridSolutions** [comment]
@ardalis I really appreciate your input but I'm not very experienced in this concept so I hope you don't mind me bothering you about this :)

I used this approach to try to use one single DbContext (for Identity and my own entities). Do you think it would be better to maintain one DbContext for Identity and a second one to work with my own tables that will be related to Users and Roles table from identity? 

Thank you!

**Comment by ardalis** [comment]
Yes, I usually try to keep identity concerns out of my domain model. You'll see an example in the eShopOnWeb sample here:

https://github.com/dotnet-architecture/eShopOnWeb/tree/master/src/Infrastructure

This lets you keep identity concerns from polluting your model. You can put them into separate databases, if you want, but it's not required. You can link your domain model's `Employee` or `Customer` or whatever to the identity users by just using a key column (typically with no foreign key on it). This would also let you switch to another identity option or provider (OpenID or whatever) without having to change your domain model. As long as there is some key to the user in your identity system, your model will still work.
