### ISSUE TITLE
Suggestion for replacement of "StructureMap".

### ISSUE THREAD

**Issue by luizs81** [ardalis/CleanArchitecture#26]
As the development of "StructureMap" has been discontinued, is there any good replacement for it?

Their website suggest using [Lamar](https://jasperfx.github.io/lamar), but their current build seems to be failing, so I'm not very confident in adding it in my project.

Thanks!

**Comment by camainc** [comment]
AutoFac or SimpleInjector are two that I have gone with. 

https://autofac.org/

https://simpleinjector.org/index.html

**Comment by fabercs** [comment]
Except the conventions mentioned [here in Readme document](https://github.com/ardalis/CleanArchitecture/blob/master/README.md#the-web-project) what are the other benefits of using an external IoC container rather than .net core's built in? I did not get it. Btw, I think StructureMap part should be completely removed as project code makes use of .net core's container.

**Comment by ardalis** [comment]
I'm planning on swapping in AutoFac. PR welcome if someone gets to it first.

**Comment by Van-Dame** [comment]
Please excuse my ignorance but what makes the default .NET Core DI unfit for the job?

**Comment by luizs81** [comment]
I guess that @ardalis wants to completely detach the `infrastructure` project from the `web`, binding the interfaces and implementations on runtime, but the built in DI doesn't allow that.

But I can be wrong.. ;)

**Comment by ardalis** [comment]
@luizs81 that's one reason, yes, although you probably could achieve that, too. The main reason is that I like some of the features that other DI containers offer, such as default conventions/policies for wiring up types to interfaces. You can easily wire up all types that match this pattern: IFoo <-> Foo for instance, so that as long as you use that naming convention you don't need to remember to touch Startup every time you add another interface and service implementation. Many small projects don't need anything more than the built-in DI container but larger ones may benefit from the features offered by Autofac, et al.

**Comment by ratanparai** [comment]
@ardalis I didn't know that it was possible!

**Comment by cal5barton** [comment]
Any reason you chose Autofac over the replacement [Lamar](https://jasperfx.github.io/lamar/documentation/ioc/), the replacement to Structuremap?

**Comment by ardalis** [comment]
That's a good question. Mostly because I hadn't kept up with its progress and because Autofac I knew from when I wrote the ASP.NET Core Docs was a fully supported container from the 1.0 days. I should look into Lamar, though, especially since my first glance at it seems to indicate it's 
a) very much like StructureMap
and
b) designed to work closely with ASP.NET Core's DI system.

Thanks!
