### ISSUE TITLE
How to adapt the clean approach when project uses stored procedures.

### ISSUE THREAD

**Issue by a-martynov** [ardalis/CleanArchitecture#291]
Hi Steve, 
My question is : if the application I   need to move from .net 4.8 (pretty big) to .net 6 does have data-access layer based on two  hundred of stored procedures, and I cannot get rid of them, can I consider approach of clean architecture and your template 
but adapt it to work with some data-access  code working with my old procedures ? So DB Context will be needed only for calling SPOCs (for crud operations).

My team and me are planning moving to new .net gradually and your advice would help us, thanks.

By the way, we are using N-tier architecture (controllers, services, data-access layers), our front end is via Angular(which won't be affected). Our stored procedures are mostly for optimisation purpose but having some logic inside them.

**Comment by ardalis** [comment]
Yes, though you'll probably have a much larger set of data access classes in your Infrastructure project than I show here by default. You might need a separate method to model every stored proc.

If you're looking for guidance on migrating from .NET 4.x to ASP.NET Core you may want to read this ebook:

https://docs.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/

This is also a process many teams enlist my company, NimblePros.com, to assist with.

Good luck!

**Comment by a-martynov** [comment]
> 

Great thanks!

**Comment by laksh-parab** [comment]
So are you recommending to add new method for each stored proc in IRepository?

**Comment by ardalis** [comment]
If necessary, or create logically grouped Query services/classes for that purpose. It depends a bit on the functionality of the SPROC how I would do it. Repositories should be just simple CRUD, at most with a specification to help shape the result. More complex operations that span many entities and/or aggregates should not be added to repositories but modeled as separate Query objects or services. Makes it easier to follow SOLID that way, especially SRP and OCP (and ISP) since you're not constantly adding to your repo interfaces/implementations.
