### ISSUE TITLE
Is Dispatching domain events after savechanges always a good idea?

### ISSUE THREAD

**Issue by paulvanbladel** [ardalis/CleanArchitecture#33]
I hope you don't mind i'm asking a question here. If so, apologies and simply disregard the question.
I saw that you dispatch the domain events after you execute savechanges.
That would be ok for me, for types of actions that should not rollback the current 'transaction'.
.e.g, after placing and order we send as domain event an email. When that email fails the original place order transaction should not be rollbacked.
On the other hand, there could be domain events which are logically part of the current transaction. So, if they fail, the whole transaction should fail as a whole.
So, I would foresee an event dispatcher before save changes and one after.
What is your view on this?
Thanks.

**Comment by paulroho** [comment]
I think it is most important to note, that an event is typically considered a fact that has already happened in the past (refer to e.g. http://blog.leifbattermann.de/2017/04/21/12-things-you-should-know-about-event-sourcing/).

Therefore in your example, if an order has been placed, an event OrderPlaced (past tense) would be stored. This is the fact. If, in reaction to that event, an email should be sent out, another aggregate could react to that event  and trigger an appropriate command e.g. SendOrderNotification (imperative). Placing this command expresses the intent of an action to be done. Executing the command could just work fine or fail. If sending the email fails, it would probably be the aggregate responsible for sending notifications to deal with this situation, e.g. retry or use a different channel to confirm the order to the customer.

As by the blue book, an aggregate is considered a transaction boundary. This means that either everything considered as part of an atomic operation can be safely fulfilled within a single aggregate, or the invariants - as often expressed in the requirement - have to be challenged. The third option would be to enter the world of eventual consistency.

**Comment by ardalis** [comment]
This solution doesn't go into event sourcing (see @paulroho comment above), but I do distinguish between pre- and post-persistence events. Pre-persistence events fire immediately when the event is raised, while post-persistence events are queued and then dispatched once persistence is successful. The reason for the distinction is primarily a practical one - you don't want to send an email thanking a customer for an order only to find that it doesn't get saved and so you have no record of it. Obviously, you could try to design your system so that it can recover from any error and no order is ever lost, but in my experience most applications lack this capability, so it's easier to avoid the problem. You avoid it by only dispatching events that have side effects outside of the system after persistence has succeeded.

I discuss this distinction more here:

http://www.weeklydevtips.com/022
and
http://www.weeklydevtips.com/023

For pre-persistence events, you can use something like Udi Dahan's [static DomainEvents class](http://udidahan.com/2009/06/14/domain-events-salvation/)
or [MediatR](https://github.com/jbogard/MediatR).
