### ISSUE TITLE
Does it make sense to have an external package dependency in a Core project?

### ISSUE THREAD

**Issue by SulimanKH** [ardalis/CleanArchitecture#397]
https://github.com/ardalis/CleanArchitecture/blob/387bd443bbd53e64f4234ab88b8e9440ed7a23e9/src/Clean.Architecture.Core/Services/ToDoItemSearchService.cs#L1

* For my use-case I would rather use a different result-object to return from Core, that is not http-specific and implement maybe a mapper in the `Infrastructure` project.

I would love to hear your thoughts!

**Comment by samuelwine** [comment]
I would suggest that there is nothing inherently wrong in Core having a dependency on an external package. Every Core project takes a dependency on the framework it is built on, which is fine, because Core is **truly** dependant on the chosen framework.

The concept that Core should not have dependencies comes from this: All code (not just Core) should be designed in a way that it does not have **unnecessary** depedencies. As Core is meant to express only the pure business logic, it follows that any dependencies on lower-level parts of the codebase are due to sub-optimal design, and are by nature unnecessary dependencies.

Therefore if there is an external package that is deemed necessary to assist Core in its functionality, that is a true dependency and there is no reason to refrain from depending on it.

**Comment by SulimanKH** [comment]
Thanks for the answer!

**Comment by Gabriel-DC** [comment]
Excellent answer, as a complement to it, it is important to point out that if a Core project has a dependency, it must have its use in a decoupled way, that is, used in an abstracted way, because if the dependency becomes deprecated, stay easier to replace with another dependency or implemented code.

It's just a thought of mine for long term on Core projects, correct me if I'm wrong 😊

**Comment by samuelwine** [comment]
That's absolutely true, but would it be fair to say that any dependency in any code should ideally be written in this way?

**Comment by ardalis** [comment]
Agreed with answers above. One more to add:

The "rule" about Core and dependencies is that it shouldn't have any that couple it to **infrastructure** or implementation details. Pure code libraries like Result, GuardClauses, FluentValidation, etc are fine since they don't bring in any non-code dependencies.

If you don't like a particular library used in this template, you're certainly welcome to swap it out. You can even fork this repo and make your own version with the libraries you prefer. It's all open to use however works best for you.
