### ISSUE TITLE
Is it clean to have Autofac Referenced in Infrastructure?

### ISSUE THREAD

**Issue by matt-lethargic** [ardalis/CleanArchitecture#43]
I've been looking through the code, I like it and it is very similar to how some projects I've written are laid out. I have an issue though with referencing Autofac in the DomainEventDispatcher class and therefore in the Infrastructure project. 

As the web project acts as the composition root shouldn't this be the only place that uses an IoC container?  I work with some legacy projects that have Ninject referenced into internal Nuget packages and it's making it very hard to move away from Ninject cleanly or easily.

**Comment by ardalis** [comment]
It's not unusual in my own projects for me to end up making a decision to rely on a particular IoC container throughout my entire architecture, because it provides some cross-cutting beneficial behavior. Most often, this is event-related, such as if I use [Udi Dahan's static DomainEvents class](http://udidahan.com/2009/06/14/domain-events-salvation/), which relies on StructureMap (but could easily be modified to use another container). Often in that case it's not only in Infrastructure, but in Core or perhaps SharedKernel.

In an ideal world, I agree with you that the container would only be in the composition root / application entry point. However, this is one area where pragmatism often leads me to accept the dependency, at which point I just try to limit how many places know about the container implementation (typically just one class in a given project). As long as you're limiting it to 1-2 classes per project that know about the container implementation, I don't think it's too bad from a coupling/technical debt perspective.

I'm curious how you're using Ninject in your legacy projects that's making it hard to switch to another implementation. That sounds like you have many integration points with Ninject, which I agree is not ideal.

**Comment by ardalis** [comment]
Closing. Feel free to reopen if you have more questions.
