### ISSUE TITLE
AmbiguousMatchException: The request matched multiple endpoints

### ISSUE THREAD

**Issue by sarazababajani** [ardalis/CleanArchitecture#499]
- .NET SDK Version: .NET core 6.0.402

Steps to Reproduce:

1. Create at least two controllers 
2. Create the same action method in both controllers (for example: Edit)
3. Create Views for each controller
4. Add a button to each view that calls this action method
5. Run the application and click the button in any of these views.

I don't face the same issue in a normal asp.net core 6.0 application so the issue is related to Ardalis clean architecture template.

**Comment by danihengeveld** [comment]
I don't think the issue is related to the template but to the way in which FastEndpoints registers the Endpoints. If your endpoint classes have the same name, you will get an AmbiguousMatchException. 

Not valid:
_/Contributor/List.cs
/Project/List.cs_

Valid:
_/Contributor/ListContributors.cs
/Project/ListProjects.cs_

**Comment by danihengeveld** [comment]
I think this issue can be closed @ardalis
