### ISSUE TITLE
Can you explain how to  implement Authentication and Authorisation please

### ISSUE THREAD

**Issue by rasikas** [ardalis/CleanArchitecture#50]
Can you explain how to implement authentication and authorisation here, as I believe we cannot add this to presentation (controllers) according to the clean architecture. It must be in Application tier, if so how to do this with available features, thank you

**Comment by ardalis** [comment]
Yes, I should do this.

In the meantime, check out how it's done here:
https://github.com/dotnet-architecture/eShopOnWeb

**Comment by rasikas** [comment]
@ardalis Thanks for the reply, yes I checked that and it seems it follows standard authentication and authorization pattern used in normal MVC where adding the [Authorize] attribute in the controller classes, I specifically asked the question because you mentioned in one of your presentations, it is always good to move any application specific logic into application layer instead of keeping it in presentation, ex: if we re-package the application to be a console app or Desktop app where we have to write the security logic again for the presentation layer. I'm not sure this can be easily done as over many years we used to use Authentication and Authorisation logic using attributes in controllers. Thanks a lot

**Comment by ardalis** [comment]
If you have more complex Auth logic I do recommend encapsulating it in your model using something like this:
 https://ardalis.com/favor-privileges-over-role-checks

This can be decoupled from how you determine who the user is.

**Comment by rasikas** [comment]
@ardalis Thanks Steve, I was just thinking out loud whether .NET core has provided something to help moving authentication/authorization to the Application layer, yes the article you provided makes sense.

**Comment by Xeinaemm** [comment]
@rasikas You can look at my implementation of the IdentityServer4 with ASP.NET Core Identity: [SpaTemplate](https://github.com/Xeinaemm/SpaTemplate) and library that's shipped with this template: [Xeinaemm.Standard](https://github.com/Xeinaemm/Xeinaemm.Standard).

At this moment I'm not deploying packages to NuGet, so you need to add extra NuGet repository due to this [line](https://github.com/Xeinaemm/SpaTemplate/blob/a2ddf8391a11c2a1314915f78f57c82f9ba56be3/Directory.Build.targets#L7). It's a relative to the root path of all solutions that you will fork from Github.

You just need to click F5 to build. Everything with deploy to the NuGet repository will be automatic.

At this moment I'm writing code, so I don't have time to create documentation. It will be shipped soon :-)

**Comment by efleming18** [comment]
@rasikas Am I ok to close this issue with the information @ardalis and  @Xeinaemm provided?

**Comment by rasikas** [comment]
Yes that's ok I will close it
