### ISSUE TITLE
Template Doesn't Work and Breaks Other Projects

### ISSUE THREAD

**Issue by zuidell** [ardalis/CleanArchitecture#646]
- .NET SDK Version: 8.0.100 (mac)

Steps to Reproduce:

1. dotnet new install Ardalis.CleanArchitecture.Template
2. dotnet new clean-arch -o 2023-12-example
3. note project references include /_2023 instead of /2023.
4. Replace all references to correct, and there were one or two others, repeat until project loads
5. Build results in errors

6. Go to any existing project
7. dotnet build
8. observe NuGet Error NU1008
9. open project/obj/project.assets.json
10. observe 9 Ardalis references which are not part of that project.

12. dotnet new uninstall Ardalis.CleanArchitecture.Template

13. mkdir fresh
14. cd fresh
15. dotnet new webapi
16. dotnet build
17. observe NuGet Error NU1008

**Comment by zuidell** [comment]
If you find this problem, you can search your disk for Directory.Packages.props and Directory.Build.props.  Delete those and the standard templates will start working again.  For some reason this template dumped them in my root code directory, which impacted all projects.

**Comment by ardalis** [comment]
New templates don't yet support Directory.Packages.props and similar files. Hopefully this will be improved in .NET 9. For now I can only apologize. I'm not going back to per-project references (because that sucks) but I recognize that you need to adjust any new project. There is a great tool that makes this easier here:
https://github.com/Vannevelj/directory-packages-props-converter
