### ISSUE TITLE
Test case ReturnsTwoContributors() fails

### ISSUE THREAD

**Issue by yogyogi** [ardalis/CleanArchitecture#682]
Test function `ReturnsTwoContributors()` fails.

- .NET SDK Version: 8.0

Steps to Reproduce:

1. Download the repository.
2. Run all the tests and will see `ReturnsTwoContributors()` is failing. 

The error screenshot:

<img width="305" alt="test-error" src="https://github.com/ardalis/CleanArchitecture/assets/13145917/f9ad857a-06a4-41c6-8859-04616ed43823">

Error Message:

```
Message: 
System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).

Stack Trace: 
HttpResponseMessage.EnsureSuccessStatusCode()
HttpClientGetExtensionMethods.GetAndDeserializeAsync[T](HttpClient client, String requestUri, ITestOutputHelper output)
ContributorList.ReturnsTwoContributors() line 16
--- End of stack trace from previous location ---
```

**Comment by yogyogi** [comment]
I have provided error message itself.

**Comment by ParsaMehdipour** [comment]
As shown and commented in the code, the database is InMemory and the query will not execute

![image](https://github.com/ardalis/CleanArchitecture/assets/75223567/57133559-adf2-47a4-8618-1bf609c86df3)

**Comment by ParsaMehdipour** [comment]
If you want the test to pass you can use the LINQ query instead of SQL raw query

**Comment by yogyogi** [comment]
@ParsaMehdipour I think all test should pass beforehand. People should not have to do manual settings on the fresh download copy.

**Comment by mickymcq** [comment]
The issue appears to be two things. The column name needs to be aliased to `PhoneNumber` (to work with `ContributorDTO`) and NULL values need to be set to an empty string since `PhoneNumber` on the `ContributorDTO` is `string` and not `string?`. Updating the SQL to the following allows the test to pass (at least for sqlite which is the current default I believe):

```SELECT Id, Name, COALESCE(PhoneNumber_Number, '') AS PhoneNumber FROM Contributors```

I'll submit a PR for the change if no one has any objections?
