### ISSUE TITLE
Question: Existing Database / Refactor 

### ISSUE THREAD

**Issue by whreed** [ardalis/CleanArchitecture#75]
Say I have an existing database that doesn't allow me to use the BaseEntity with the id property because primary keys are not uniform and are different per table.  How can I refactor the clean architecture to have the primary keys be present in each entity instead of within an base class?  I do not want to have to change each table and many rows of data and keys to support this structure and nor do I want to start a new database to conform to this.  Is it possible?  I mean I could just start with a new database if that is the last possible resort to start using this architecture as a baseline.  Thanks in advance.

Will

**Comment by ardalis** [comment]
Usually I solve this by using `BaseEntity<TKey>` (or `IEntity<TKey>`). Then the class would look something like this:

```
public class BaseEntity<TKey>
{
    public TKey Id { get; set; }
}
```
and entities:
```
public class Customer : BaseEntity<int>
{}
public class Order : BaseEntity<Guid>
{}
```

**Comment by Excone** [comment]
That would make sense for the primary key, but the foreign keys inside the class must also be updated via some generic way.

**Comment by ardalis** [comment]
EF sorts that out based on the PK of the type that the FK is referencing. If there is a specific problem you’ve seen can you describe it?

**Comment by Excone** [comment]
Suppose I have the following BaseEntity class:

<code>
public class BaseEntity<TKey>
{
    public TKey Id { get; set; }
}
</code>

and I'm inheriting this class like this:

<code>
public partial class NewsType : EntityBase<int>
    {
        public NewsType()
        {
            News = new HashSet<News>();
        }

        public string Name { get; set; }

        public virtual ICollection<News> News { get; set; }
    }
</code>

Now, if I reference this class from another class as foreign key, I have to manually update the reference type (int) if I change T in EntityBase<T> to Guid:

<code>
public partial class News : EntityBase<int>
    {
        public int NewsTypeId { get; set; } // Should also change this to new Id type (Guid)
        public DateTime Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public virtual NewsType NewsType { get; set; }
    }
</code>

So, we need a way to pass the primary table's Id type also to foreign key references.

We also need to update them inside the ViewModels and service layer.

Correct me if I am wrong, but using EntityBase<T> does not solve anything in this regard.

**Comment by ardalis** [comment]
I see. Yes, you're right, if you change your ID types around frequently this could be a problem. In my experience, the type of the key for an entity is generally determined when it is first created, and rarely changed (or, if changed, it's only changed once). So it's not usually a huge problem when that occurs to locate and update the places where it would need to be modified. It *can* be important to have generic features like a generic repository work with whatever type of key the entity has, for instance when using a method like `GetById(TKey key)`  which is why it is necessary when using different types of keys to add the generic key type to `BaseEntity`.

Sorry I don't have an elegant solution for the FK/ViewModel key references.

**Comment by whreed** [comment]
I understand what you are saying in your original reply @ardalis  but what happens if your primary key is not named Id, your example says when Id is a different type...

**Comment by ardalis** [comment]
I would name it Id. Otherwise you're just making your life harder. If you can't control what the database will use, or if you prefer database ID columns be named [tablename]_id or something similar, you can configure this using EF's fluent configuration.

Assuming you don't want the C# class IDs to be named `Id` can you share why not and what problem that's solving?

**Comment by whreed** [comment]
Ah great point about the fluent configuration.  I will look into that.   Thank you for the insight!  Keep up the great work!

**Comment by whreed** [comment]
Sorry I should've answered your last message.  I am inheriting a database of statistics that are generated from another program and it's historical over a few years and has many other tables using the keys. This db was set up by a user that was probably not dba (it's a site that uses sports stats) and I would like to build a new site that utilizes your framework (probably more like eshopweb) ...so I didn't want to have to edit his db but to have this working correctly or the better way I may have to rename keys going forward.  I can just set up another db and update items.  BTW I ported this (eshopweb) over to MySQL using migrations and the pomelo framework, worked great with a small modification to the migration files.
