### ISSUE TITLE
Web Project: Remove unused references

### ISSUE THREAD

**Issue by sadukie** [ardalis/CleanArchitecture#761]
Running Clean Architecture template 9.1.2 with .NET 8.0.300

Saw these in the Web project. Are these still needed?

```xml
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
   <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" PrivateAssets="All" />
```
I removed them from my project locally and am not seeing any side effects.

**Comment by Emopusta** [comment]
Hello,

First of all, if you remove `Microsoft.EntityFrameworkCore.Design` you won't be able to use migration or update database at the initialization of the project because it includes `dotnet ef migrations ...` etc. so this package necessary for database initialization operations.

In the other hand, `Microsoft.VisualStudio.Web.CodeGeneration.Design` seems auto added when the scaffolding operation. I am depending on this stackoverflow [answer](https://stackoverflow.com/a/58514733/14473087) about scaffolding auto package addition. I searched inside the repo and I could not find anything about `dotnet aspnet-codegenerator *` except #12 pull request but it has lack of relevancy with this situation so we may delete that package.
