### ISSUE TITLE
[Question] Entities used in the Web project

### ISSUE THREAD

**Issue by KrisPetkov** [ardalis/CleanArchitecture#77]
I have a quick question:

Is it OK if we are using Entities from the core layer of the clean architecture into the Web project (the presentation layer)? 
I saw [HERE](https://github.com/ardalis/CleanArchitecture/blob/fd70a63e1f2667bec0280b09a856c7a343626553/src/CleanArchitecture.Web/Controllers/ToDoController.cs#L2) that we have a dependency to the Entities from the core layer. Doesn't this brakes the principle of the Clean Architecture that we do not have to depend on the core dependencies?

Thanks in advance!

P.S. Any explanation with more details will be appreciated.

**Comment by Xeinaemm** [comment]
You are right, it's not right. This template defines three different approaches to building UI (MVC, Pages, and SPA). In SPA you can split projects but in MVC and Pages, you cannot.

In my opinion, we can define the project for contracts - shareable models between UI, API, and Core. We can use T4 templates or the heaviest approach - NSWAG to create clients for SPA.

I'm using contracts for API and T4 for SPA. It compromises between duplication and a "clean" approach.

**Comment by KrisPetkov** [comment]
I'm trying to figure out the best approach for a MVC project. 

@Xeinaemm what do you mean by "define the project for contracts - sharable models"?
Is it that we can extract the models as a separate project referenced by every level of the Clean Architecture or something else? And if yes - what is the right way to map them with the Domain entities (in which layer or which approach to use)

**Comment by Xeinaemm** [comment]
Contracts? In most cases, something that you want to share without duplication(read models), API endpoints(generated by Refit in my case)m commands' models and service broker messages. 

I'm splitting API into ReadAPI with Contracts.API(general purpose) that allows you to create only data with predefined models that you want to share internally and externally(for example different domains want data that you normally share because it's your domain - for example you can use Github API. I'm going further and predefining API calls with Refit and models for that). 

On the other hand, PresentationAPI with Contracts.PresentationAPI handles internal read/write(CQRS). In this case, it's something that you don't want to share externally but use in UI like read models for views and commands models for actions. In SPA you can use this to generate APIs and models for JS or TS.

Read models are simple - read what you want from DB without knowing how the domain is created.

In write mode, you need to create commands that handle changes of domain models and models change themselfs or propagate domain events further.

I want to mention that this approach is for monolith that going into microservices(60+ internal systems and more than 150 services), in most cases simple CQRS that just split read models from write models will be enough.

My colleague created very good DDD example: [here](https://github.com/kgrzybek/modular-monolith-with-ddd )

**Comment by ardalis** [comment]
You're correct; it would ideally use a DTO for the items returned. I'll make a note to fix it or if someone wants to add a simple pull request with a fix I'd consider it.

**Comment by efleming18** [comment]
Resolved in the linked PR.
