### ISSUE TITLE
[Question] Aggregate Root Methods Accepting a DTO as Parameter allowed?

### ISSUE THREAD

**Issue by malohr** [ardalis/CleanArchitecture#80]
So my question is simple:

As an example, if I have a simple create command (DTO containing a List of Product DTO’s) received from the Controller Endpoint and forwarded to a CommandHandler via Mediator) and there are many properties that I have to set in the Aggregate method, would it be ok when I pass the DTO to the method instead of each parameter (see example below) ? 

```
public class Cart {
   
    private readonly List<Products> _products = new List<Products>();
    public IReadOnlyList<Products> Products => _products.AsReadOnly();

    public void AddProducts(List<MyProductDTO> dto){
           foreach(var p in dto){
                 Product newProd = new Product(dto.ProductName, ...)
                 _products.Add(newProd);
           }
    }
}
```

**Comment by alex-cavalleri** [comment]
Is it OK to have a DTO as a method parameter? IMHO, yes, but this could give you some problems:

- Performance: Let's suppose that you have a CommandHandler which receives an ICreateProductsCommand which contains a ICreateProductCommand - you now need to map all of the ICreateProductCommands into a list of "MyProductDTO": products could be created from different handlers and different handlers have different commands

- Readability and documentation: Passing a DTO as a parameter gives you less comprehension of what your constructor needs, having a simple method with regular arguments also allows you to create documentation (you just need to type three "/" in visual studio) for every specific parameter

Also, in your code I see that you're adding a list of products in your constructor. You might want to have something like this 

    public class Cart {
   
        private readonly List<Products> _products = new List<Products>();
        public IReadOnlyList<Products> Products => _products.AsReadOnly();

        public void AddProducts(List<MyProductDTO> dto){
               foreach(var p in dto){
                     AddProduct(dto);
               }
        }
    
        public void AddProduct(MyProductDTO dto){
               Product newProd = new Product(dto.ProductName, ...);
               _products.Add(product);
        } 
    }

This will give you more flexibility, you can ether call AddProduct to add a single product or call the AddProducts to add multiple products without instantiating a list for one item, which is unclear and confusing. 
I also suggest you to use IList instead of List.

**Comment by ardalis** [comment]
You can use a DTO but usually I wouldn't. The biggest reason is that the DTO is usually associated with your wire format for your UI. You want to follow separation of concerns so that if you need to change your domain model it doesn't immediately mean you have to change your customer-facing API definition (represented by the DTO in your example), and vice versa. So, typically I will define the DTOs in the UI project since they're a UI concern, and I will map to/from domain objects in the UI or application layer (usually co-located in the UI project so it can access the DTOs).

What does this mean for your domain? If you're going to use constructors to provide required values to your domain objects (which is generally a good thing even if some ORMs like EF/EF Core make it difficult sometimes), then you'll need to pass the properties from the DTO(s) to the constructor as you've shown. If that's tedious and you'd like to automate it somehow, I recommend using a tool like AutoMapper, which [can be configured to use constructor arguments].(https://stackoverflow.com/questions/2239143/automapper-how-to-map-to-constructor-parameters-instead-of-property-setters).

Hope that helps.

**Comment by jaylensoeur** [comment]
I agree with you @ardalis. However, why is https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures
saying that "The Application Core holds the business model, which includes entities, services, and interfaces. These interfaces include abstractions for operations that will be performed using Infrastructure, such as data access, file system access, network calls, etc. Sometimes services or interfaces defined at this layer will need to work with non-entity types that have no dependencies on UI or Infrastructure. These can be defined as simple Data Transfer Objects (DTOs)."

Application Core types:
- Entities (business model classes that are persisted)
- Interfaces
- Services
- DTOs

I would have thought DTOs would have been more appropriate in the Infrastructure and UI (Frameworks and Drivers layer). like how you have implemented it in this code base.

![](https://blog.cleancoder.com/uncle-bob/images/2012-08-13-the-clean-architecture/CleanArchitecture.jpg)

**Comment by ardalis** [comment]
DTOs *can* live in Core, typically, as long as they do not reference any types that aren't either in the framework or in Core (e.g. a ViewModel or DbContext etc.). Whether or not it makes sense to include DTOs in Core, especially if they're only used by Infrastructure or UI types is a design choice. There's nothing in Clean Architecture that would prevent putting them in Core since they don't break the rule of pulling extra unwanted dependencies there.
