### ISSUE TITLE
Feature Request: Use Cases / Organize by Feature

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#82]
Demonstrate how to use a feature folder / use cases organization for the solution template.

See #21, #37, #66 for background.

**Comment by rfpedrosa** [comment]
@ardalis I see this open for a while and I'm wondering if this is something in your list in a near future? I'm also wondering if you have any thoughts about domain/ApplicationCore (something like [how it is done in the API](https://github.com/ardalis/CleanArchitecture/tree/master/src/CleanArchitecture.Web/Endpoints/ToDoItems)) and if some help is needed?

**Comment by ardalis** [comment]
1. Not sure how soon I'll get to it. Could be a good topic for an upcoming stream on my twitch.tv/ardalis stream on Fridays. But right now I've got a bunch of other work I need to get done, first.
2. Not sure what thoughts you're looking for, can you elaborate? What does domain/applicationcore have to do with how the api endpoints are set up in the web project?

**Comment by rfpedrosa** [comment]
1. watching 👍 
2. Correct If I'm wrong but one of the advantages of using [API endpoints](https://github.com/ardalis/CleanArchitecture/tree/master/src/CleanArchitecture.Web/Endpoints/ToDoItems) "[is to avoid MVC Controllers as an antipattern](https://github.com/ardalis/ApiEndpoints#motivation)". I believe that is great because when an API gets bigger, a [feature organization](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/develop-asp-net-core-mvc-apps#feature-organization) is usually preferable. However, [when I look at the domain](https://github.com/ardalis/CleanArchitecture/tree/master/src/CleanArchitecture.Core), everything seems to be organized by type? 

- What I'm currently doing: I have a [AggregateRootName] sub directory in every domain folder (if applicable). I mean, Events -> UserAggregate, Exceptions -> UserAggreate, and so on.
- alternative (domain directories):
- UserAggregate
  -- Events
  -- Exceptions
  -- Entities
- BasketAggregate
  -- Events
  -- Exceptions
  -- Entities

I'm wondering if you have any thoughts? or what were your thoughts when you got this feature requested created?

**Comment by ardalis** [comment]
I agree with your organization of the Domain Model in Core as far as grouping by aggregates and putting aggregate-specific things in those folders, rather than having top level folders for all the things like entities, services, etc.

The trick is, with a basically empty solution template, it's hard to show a vertical slices organization when there's not much there yet. Maybe I'll extend what's in the template so that I can show this kind of grouping.

**Comment by ardalis** [comment]
I'm working on this in my `ardalis/project-aggregate` branch. It's incomplete so far but will show organization by aggregate which will be a better and more feature-oriented organization.

**Comment by rfpedrosa** [comment]
@ardalis thanks for the feedback. Let me know if help is welcome. I may have a bit availability by the end of this week.

**Comment by ardalis** [comment]
I'll try to wrap it up during my stream on Friday. If you want to join via comments or a skype call let me know. Should be 3-5pm EST.
